#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
UniPool Dashboard — 실행 순서 및 핵심 로직 코드 가이드 PDF 생성기
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY

# ── 한글 폰트 등록 ──────────────────────────────────────────────────────────────
pdfmetrics.registerFont(TTFont(
    'Korean',
    '/System/Library/Fonts/Supplemental/AppleGothic.ttf'
))
pdfmetrics.registerFont(TTFont(
    'KoreanBold',
    '/System/Library/Fonts/Supplemental/NotoSansGothic-Regular.ttf'
))
pdfmetrics.registerFontFamily('Korean', normal='Korean', bold='KoreanBold',
                               italic='Korean', boldItalic='KoreanBold')

OUTPUT_PATH = "/Volumes/code/ra2tech/front2/unipool-dashboard-guide.pdf"

# ── Colors ─────────────────────────────────────────────────────────────────────
C_DARK      = HexColor("#0f172a")
C_SLATE     = HexColor("#475569")
C_INDIGO    = HexColor("#6366f1")
C_GREEN     = HexColor("#16a34a")
C_CODE_BG   = HexColor("#f1f5f9")
C_CODE_BDR  = HexColor("#cbd5e1")
C_HEAD_BG   = HexColor("#e0e7ff")
C_SEC_BG    = HexColor("#f8fafc")
C_NOTE_BG   = HexColor("#eef2ff")
C_NOTE_TEXT = HexColor("#3730a3")

# ── Document ───────────────────────────────────────────────────────────────────
doc = SimpleDocTemplate(
    OUTPUT_PATH, pagesize=A4,
    leftMargin=2*cm, rightMargin=2*cm,
    topMargin=2.5*cm, bottomMargin=2.5*cm,
    title="UniPool Dashboard 코드 가이드", author="ra2tech"
)
W = A4[0] - 4*cm  # 사용 가능 폭

# ── Styles ─────────────────────────────────────────────────────────────────────
def S(name, **kw):
    return ParagraphStyle(name, **kw)

TITLE   = S("T",  fontName="KoreanBold", fontSize=24, leading=32,
             textColor=C_DARK,  alignment=TA_CENTER, spaceAfter=8)
SUBTT   = S("ST", fontName="Korean",    fontSize=13, leading=18,
             textColor=C_SLATE, alignment=TA_CENTER, spaceAfter=16)
H1      = S("H1", fontName="KoreanBold", fontSize=15, leading=20,
             textColor=C_DARK,  spaceBefore=16, spaceAfter=6,
             backColor=C_HEAD_BG, leftIndent=4, borderPad=5)
H2      = S("H2", fontName="KoreanBold", fontSize=12, leading=16,
             textColor=C_INDIGO, spaceBefore=12, spaceAfter=4)
H3      = S("H3", fontName="KoreanBold", fontSize=10, leading=14,
             textColor=C_DARK,  spaceBefore=8, spaceAfter=3)
BODY    = S("B",  fontName="Korean",    fontSize=9.5, leading=15,
             textColor=HexColor("#1e293b"), spaceAfter=5, alignment=TA_JUSTIFY)
BLET    = S("BL", fontName="Korean",    fontSize=9.5, leading=15,
             textColor=HexColor("#1e293b"), spaceAfter=3,
             leftIndent=12)
NOTE    = S("N",  fontName="Korean",    fontSize=9, leading=13,
             textColor=C_NOTE_TEXT, backColor=C_NOTE_BG,
             leftIndent=8, rightIndent=8, spaceBefore=4, spaceAfter=6,
             borderPad=4)
CODE    = S("CD", fontName="Courier",   fontSize=7.2, leading=10.5,
             textColor=HexColor("#1e293b"), backColor=C_CODE_BG,
             leftIndent=0, rightIndent=0, spaceAfter=0, spaceBefore=0)
CMNT    = S("CM", fontName="Korean",    fontSize=7.2, leading=10.5,
             textColor=HexColor("#64748b"), backColor=C_CODE_BG,
             leftIndent=0, rightIndent=0, spaceAfter=0, spaceBefore=0)

# ── Helpers ────────────────────────────────────────────────────────────────────
def sp(n=6):  return Spacer(1, n)
def hr():     return HRFlowable(width="100%", thickness=0.5,
                                 color=C_CODE_BDR, spaceBefore=4, spaceAfter=4)
def h1(t):    return Paragraph(t, H1)
def h2(t):    return Paragraph(t, H2)
def h3(t):    return Paragraph(t, H3)
def body(t):  return Paragraph(t, BODY)
def blet(t):  return Paragraph(f"• {t}", BLET)
def note(t):  return Paragraph(f"※ {t}", NOTE)

def tbl_style(header=True):
    s = [
        ("FONTNAME",  (0,0), (-1,-1), "Korean"),
        ("FONTSIZE",  (0,0), (-1,-1), 8.5),
        ("GRID",      (0,0), (-1,-1), 0.4, C_CODE_BDR),
        ("VALIGN",    (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING",  (0,0), (-1,-1), 6),
        ("TOPPADDING",   (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0), (-1,-1), 4),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [white, C_SEC_BG]),
    ]
    if header:
        s += [
            ("BACKGROUND", (0,0), (-1,0), C_DARK),
            ("TEXTCOLOR",  (0,0), (-1,0), white),
            ("FONTNAME",   (0,0), (-1,0), "KoreanBold"),
        ]
    return TableStyle(s)

def make_table(data, widths, has_header=True):
    t = Table(data, colWidths=widths)
    t.setStyle(tbl_style(has_header))
    return t

def code_block(lines):
    """각 줄을 한 Row로 만들어 페이지 분할이 가능한 Table 반환.
    lines: list of (text, is_comment)"""
    rows = []
    for line, is_cmt in lines:
        esc = (line
               .replace("&", "&amp;")
               .replace("<", "&lt;")
               .replace(">", "&gt;"))
        st = CMNT if is_cmt else CODE
        rows.append([Paragraph(esc if esc.strip() else " ", st)])
    t = Table(rows, colWidths=[W - 0.4*cm], splitByRow=True)
    t.setStyle(TableStyle([
        ("BOX",          (0,0), (-1,-1), 0.8, C_CODE_BDR),
        ("BACKGROUND",   (0,0), (-1,-1), C_CODE_BG),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING",   (0,0), (-1,-1), 1),
        ("BOTTOMPADDING",(0,0), (-1,-1), 1),
    ]))
    return t

# ══════════════════════════════════════════════════════════════════════════════
story = []

# ── 표지 ──────────────────────────────────────────────────────────────────────
story += [
    sp(60),
    Paragraph("UniPool Dashboard", TITLE),
    Paragraph("실행 순서 &amp; 핵심 로직 코드 가이드", SUBTT),
    sp(8), hr(), sp(6),
    body("SvelteKit + viem 기반 멀티체인 DeFi 파라미터 대시보드의 "
         "전체 실행 흐름과 각 모듈의 핵심 함수를 소스코드와 함께 설명합니다."),
    sp(10),
    make_table([
        ["항목", "내용"],
        ["프레임워크",     "SvelteKit 2  (Svelte 5 Runes)"],
        ["블록체인 라이브러리", "viem 2"],
        ["대상 체인",     "Arbitrum One / Base / BNB Smart Chain"],
        ["빌드 도구",     "Vite 8 + vite-plugin-singlefile"],
    ], [4*cm, W-4*cm]),
    PageBreak(),
]

# ── 1. 전체 아키텍처 ────────────────────────────────────────────────────────────
story += [
    h1("1. 전체 아키텍처 & 파일 구조"),
    body("앱은 SvelteKit 정적 빌드 모드(SSR 없음)로 동작합니다. "
         "브라우저가 페이지를 열면 +page.svelte가 마운트되고, "
         "3개 체인(Arbitrum·Base·BSC)의 스마트 컨트랙트 데이터를 "
         "viem 라이브러리로 직접 읽어와 카드 형태로 표시합니다."),
    sp(4),
    make_table([
        ["레이어", "파일", "역할"],
        ["라우트", "src/routes/+layout.svelte",  "앱 셸 (Sidebar + 콘텐츠 영역)"],
        ["라우트", "src/routes/+layout.ts",      "prerender=true, ssr=false 설정"],
        ["라우트", "src/routes/+page.svelte",    "메인 페이지 — 데이터 로드 & 카드 렌더"],
        ["설정",   "src/config/chains.ts",       "체인별 RPC · Factory 주소 상수"],
        ["데이터", "src/config/fetchFactory.ts", "Factory 컨트랙트 데이터 fetching"],
        ["데이터", "src/config/fetchpairs.ts",   "Pair 컨트랙트 데이터 fetching"],
        ["데이터", "src/config/fetchVault.ts",   "Vault 컨트랙트 데이터 fetching"],
        ["편집",   "src/config/editing.ts",      "Safe 트랜잭션 빌드 유틸"],
        ["상태",   "src/lib/sidebar.svelte.ts",  "사이드바 선택 상태 스토어"],
        ["컴포넌트", "src/components/Sidebar.svelte",    "필터 사이드바 UI"],
        ["컴포넌트", "src/components/FactoryCard.svelte", "Factory 데이터 카드"],
        ["컴포넌트", "src/components/PairCard.svelte",   "Pair 풀 데이터 카드"],
        ["컴포넌트", "src/components/VaultCard.svelte",  "Vault 데이터 카드"],
        ["컴포넌트", "src/components/Sparkline.svelte",  "SVG 스파크라인 차트"],
    ], [2.8*cm, 5.8*cm, W-8.6*cm]),
    PageBreak(),
]

# ── 2. 실행 순서 ───────────────────────────────────────────────────────────────
story += [
    h1("2. 실행 순서 (App Startup → Data Render)"),
    body("브라우저에서 앱을 열고 'Load all chains' 버튼을 누른 뒤 "
         "카드가 화면에 표시되기까지의 순서입니다."),
    sp(4),
    make_table([
        ["단계", "위치", "설명"],
        ["① 앱 초기화",
         "+layout.svelte",
         "앱 셸 렌더링. Sidebar 컴포넌트 마운트 후 +page.svelte를 page-content 영역에 렌더"],
        ["② 상태 초기화",
         "+page.svelte $state",
         "3개 체인 각각에 대한 ChainState 객체를 $state로 초기화. "
         "loading=false, factory=null, pairs=[], vault=null"],
        ["③ 버튼 클릭",
         "loadAll() 호출",
         "Promise.all([loadChain('arbitrum'), loadChain('base'), loadChain('bsc')]) "
         "— 3개 체인을 동시에 병렬 로드 시작"],
        ["④ Factory 조회",
         "fetchFactoryData(config)",
         "viem multicall로 13개 getter 함수를 1회 HTTP 요청으로 일괄 호출. "
         "완료 즉시 states[key].factory = factory → FactoryCard 표시"],
        ["⑤ Pair 목록 조회",
         "fetchAllPairs(config,...)",
         "① getPairAtIndex(i) 일괄 호출 → Pair 주소 목록\n"
         "② 각 Pair에 fetchOnePair 병렬 실행 (~31개 함수/Pair)\n"
         "③ 토큰 symbol·decimals ERC-20 multicall\n"
         "완료 즉시 states[key].pairs = pairs → PairCard 목록 표시"],
        ["⑥ Vault 조회",
         "fetchVaultData(config,...)",
         "① Vault 기본 정보 2개 함수 조회\n"
         "② 토큰별 4개 함수(getAssetData/Status/AaveSupport/YieldAccumulator) 일괄 multicall\n"
         "완료 즉시 states[key].vault = vault → VaultCard 표시"],
        ["⑦ Sidebar 등록",
         "sidebarStore.set*()",
         "각 단계 완료 시 사이드바 스토어에 Factory·Pair·Vault 주소 등록. "
         "체크박스 필터 사용 가능해짐"],
        ["⑧ (선택) 7일 히스토리",
         "loadHistory(key)",
         "DeFiLlama API로 7일치 블록번호 조회 → 각 블록에서 Factory/Pair 상태 순차 조회 "
         "→ Sparkline 차트에 7일 추이 표시"],
        ["⑨ (선택) 날짜 비교",
         "compareAllRange()",
         "From/To 날짜 입력 → 지정 시점 블록 조회 → 해당 블록의 컨트랙트 상태 로드 "
         "→ diff 배지로 변화량 표시"],
        ["⑩ (선택) Safe 편집",
         "openEdit → addEditToBatch",
         "✎ 아이콘 클릭 → 편집 모달 → 값 입력 → 'Add to JSON batch' "
         "→ JSON 버튼으로 Safe 트랜잭션 파일 다운로드"],
    ], [2.6*cm, 3.6*cm, W-6.2*cm]),
    PageBreak(),
]

# ── 3. chains.ts ───────────────────────────────────────────────────────────────
story += [
    h1("3. src/config/chains.ts — 체인 설정"),
    body("앱이 지원하는 3개 체인(Arbitrum·Base·BSC)의 이름, viem 체인 객체, "
         "RPC 엔드포인트 URL, Factory 컨트랙트 주소를 정의합니다. "
         ".env 파일의 환경변수를 읽어옵니다."),
    sp(4),
    code_block([
        ("import { arbitrum, base, bsc } from 'viem/chains';", False),
        ("", False),
        ("// 지원 체인: Arbitrum / Base / BSC", True),
        ("// Ethereum은 Factory가 zero address(미배포)이므로 목록에서 제외", True),
        ("export const CHAINS = {", False),
        ("  arbitrum: {", False),
        ("    name: 'Arbitrum One',", False),
        ("    chain: arbitrum,                              // viem 체인 객체 (chainId 등 포함)", True),
        ("    rpc: import.meta.env.VITE_RPC_ARBITRUM,      // .env의 Alchemy/Infura URL", True),
        ("    factory: import.meta.env.VITE_FACTORY_ARBITRUM,  // 0xa882...b6A7", True),
        ("  },", False),
        ("  base: { name: 'Base', chain: base,", False),
        ("    rpc: import.meta.env.VITE_RPC_BASE,", False),
        ("    factory: import.meta.env.VITE_FACTORY_BASE },", False),
        ("  bsc: { name: 'BNB Smart Chain', chain: bsc,", False),
        ("    rpc: import.meta.env.VITE_RPC_BSC,", False),
        ("    factory: import.meta.env.VITE_FACTORY_BSC },", False),
        ("} as const;", False),
        ("", False),
        ("// as const: 모든 값이 리터럴 타입으로 추론됨", True),
        ("// ChainKey = 'arbitrum' | 'base' | 'bsc'", True),
        ("export type ChainKey = keyof typeof CHAINS;", False),
    ]),
    sp(4),
    note("CHAINS가 'as const'이므로 ChainKey 타입이 keyof로 자동 유도됩니다. "
         "새 체인을 추가할 때 CHAINS에만 항목을 넣으면 타입이 자동 확장됩니다."),
    PageBreak(),
]

# ── 4. fetchFactory.ts ─────────────────────────────────────────────────────────
story += [
    h1("4. src/config/fetchFactory.ts — Factory 데이터 조회"),
    body("Factory 스마트 컨트랙트에서 프로토콜 전역 파라미터를 읽어옵니다. "
         "13개의 getter 함수를 단 1번의 HTTP 요청(Multicall)으로 일괄 조회하여 "
         "FactoryData 객체를 반환합니다."),
    sp(4),
    h2("4.1 FactoryData 타입"),
    code_block([
        ("export type FactoryData = {", False),
        ("  feeCollector: `0x${string}`;   // 프로토콜 수수료 수취 주소", True),
        ("  beaconAddress: `0x${string}`;  // Beacon Proxy 구현 주소 (업그레이드 앵커)", True),
        ("  vault: `0x${string}`;          // Aave에 유휴자금 예치하는 Vault 주소", True),
        ("  aavePool: `0x${string}`;       // 연결된 Aave 대출 풀 주소", True),
        ("  allPairsLength: bigint;        // 지금까지 생성된 총 Pair 수", True),
        ("", False),
        ("  fees: {", False),
        ("    feeLp: number;    // LP 수수료 (bps, 1bps = 0.01%)", True),
        ("    feePool: number;  // 프로토콜 운영 수수료 (bps)", True),
        ("    burnFee: number;  // LP 토큰 소각 수수료 (bps)", True),
        ("    loanFee: number;  // 대출 수수료 (bps)", True),
        ("  };", False),
        ("", False),
        ("  interestParams: {              // Kinked IRM 파라미터", True),
        ("    protocolFeeBps: number;      // 이자 수익 중 프로토콜 몫", True),
        ("    optimalPointBps: number;     // 이자율 커브 꺾임점 (활용도 임계값)", True),
        ("    interestRateBaseBps: number; // 0% 활용도 시 연 기본 이자율", True),
        ("    interestRateOptimalBps: number; // 최적 활용도 시 연 이자율", True),
        ("    interestRateAddBps: number;  // 최적 초과 시 추가 이자율", True),
        ("  };", False),
        ("", False),
        ("  borrowLimitBps: number;         // 최대 LTV (담보 대비 대출 한도, %)", True),
        ("  liquidationPenaltyBps: number;  // 청산 시 추가 패널티 (%)", True),
        ("  maxBorrowPerTick: number;       // 단일 틱 최대 대출 비율 (%)", True),
        ("  maxBorrowPerRange: number;      // 틱 범위 전체 최대 대출 비율 (%)", True),
        ("  priceDecay: bigint;             // 가상가격->시장가격 수렴 속도", True),
        ("  swapPriceToleranceBps: number;  // 최대 스왑 슬리피지 (%)", True),
        ("  tickBuffer: number;             // 청산 계산 시 안전 여유 틱 수", True),
        ("};", False),
    ]),
    sp(6),
    h2("4.2 fetchFactoryData() — 핵심 함수"),
    body("viem의 multicall을 사용해 13개 getter를 1번의 RPC 요청으로 일괄 조회합니다. "
         "blockNumber를 전달하면 과거 블록 시점의 상태를 조회합니다(아카이브 노드 필요)."),
    sp(4),
    code_block([
        ("export async function fetchFactoryData(", False),
        ("  config: ChainConfig,    // 체인 설정 (RPC URL + Factory 주소)", True),
        ("  blockNumber?: bigint    // 미전달: 최신 블록 / 전달: 해당 블록 시점 조회", True),
        ("): Promise<FactoryData> {", False),
        ("", False),
        ("  // 1) viem 읽기 전용 클라이언트 생성", True),
        ("  const client = createPublicClient({", False),
        ("    chain: config.chain,", False),
        ("    transport: http(config.rpc)  // Alchemy/Infura HTTPS 엔드포인트", True),
        ("  });", False),
        ("", False),
        ("  // 2) Multicall: 13개 함수를 HTTP 1회로 일괄 조회", True),
        ("  //    allowFailure:true -> 일부 실패해도 나머지 결과 반환", True),
        ("  //    blockNumber 스프레드: 미전달 시 빈 객체 {} -> 최신 블록 조회", True),
        ("  const results = await client.multicall({", False),
        ("    allowFailure: true,", False),
        ("    ...(blockNumber !== undefined ? { blockNumber } : {}),", False),
        ("    contracts: [", False),
        ("      { address: config.factory, abi: FACTORY_ABI,", False),
        ("        functionName: 'getFeeCollector' },           // [0]", True),
        ("      { ..., functionName: 'getBeaconAddress' },     // [1]", True),
        ("      { ..., functionName: 'getVault' },             // [2]", True),
        ("      { ..., functionName: 'getAavePool' },          // [3]", True),
        ("      { ..., functionName: 'getAllPairsLength' },     // [4]", True),
        ("      { ..., functionName: 'getFeesBps' },           // [5] -> [feeLp, feePool, burnFee, loanFee]", True),
        ("      { ..., functionName: 'getInterestParamsBps' }, // [6] -> 튜플 객체", True),
        ("      { ..., functionName: 'getBorrowLimitBps' },    // [7]", True),
        ("      { ..., functionName: 'getLiquidationPenaltyBps' }, // [8]", True),
        ("      { ..., functionName: 'getMaxBorrowPerTickAndRange' }, // [9] -> [maxTick, maxRange]", True),
        ("      { ..., functionName: 'getPriceDecay' },        // [10]", True),
        ("      { ..., functionName: 'getSwapPriceToleranceBps' }, // [11]", True),
        ("      { ..., functionName: 'getTickBuffer' }         // [12]", True),
        ("    ]", False),
        ("  });", False),
        ("", False),
        ("  // 3) 결과 파싱 헬퍼: results[i] 성공 시 결과, 실패 시 fallback 반환", True),
        ("  function get<T>(i: number, fallback: T): T {", False),
        ("    const r = results[i];", False),
        ("    return r.status === 'success' ? (r.result as T) : fallback;", False),
        ("  }", False),
        ("", False),
        ("  const fees    = get<readonly [number,number,number,number]>(5, [0,0,0,0]);", False),
        ("  const interest = get<InterestParams>(6, INTEREST_FALLBACK);", False),
        ("  const maxBorrow = get<readonly [number,number]>(9, [0,0]);", False),
        ("", False),
        ("  return {", False),
        ("    feeCollector:   get<`0x${string}`>(0, ZERO),", False),
        ("    beaconAddress:  get<`0x${string}`>(1, ZERO),", False),
        ("    vault:          get<`0x${string}`>(2, ZERO),", False),
        ("    aavePool:       get<`0x${string}`>(3, ZERO),", False),
        ("    allPairsLength: get<bigint>(4, 0n),  // 0n = BigInt 리터럴", True),
        ("    fees: { feeLp: fees[0], feePool: fees[1],", False),
        ("            burnFee: fees[2], loanFee: fees[3] },", False),
        ("    interestParams: interest,", False),
        ("    borrowLimitBps:        get<number>(7, 0),", False),
        ("    liquidationPenaltyBps: get<number>(8, 0),", False),
        ("    maxBorrowPerTick:  maxBorrow[0],", False),
        ("    maxBorrowPerRange: maxBorrow[1],", False),
        ("    priceDecay:           get<bigint>(10, 0n),", False),
        ("    swapPriceToleranceBps: get<number>(11, 0),", False),
        ("    tickBuffer:           get<number>(12, 0)", False),
        ("  };", False),
        ("}", False),
    ]),
    sp(4),
    h2("4.3 bpsToPercent() — 표시 유틸"),
    code_block([
        ("// 1 bps = 0.01% = 1/10000", True),
        ("// e.g. bpsToPercent(30) -> '0.30%'   bpsToPercent(8000) -> '80.00%'", True),
        ("export function bpsToPercent(bps: number): string {", False),
        ("  return `${(bps / 100).toFixed(2)}%`;", False),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 5. fetchpairs.ts ───────────────────────────────────────────────────────────
story += [
    h1("5. src/config/fetchpairs.ts — Pair 데이터 조회"),
    body("Factory에 등록된 모든 Pair(유동성 풀) 컨트랙트의 데이터를 읽어옵니다. "
         "각 Pair는 AMM 스왑 + 대출 기능을 하나의 컨트랙트로 구현합니다."),
    sp(4),
    h2("5.1 fetchOnePair() — 단일 Pair 조회 (내부 함수)"),
    body("하나의 Pair 주소에 대해 31개의 getter 함수를 multicall로 일괄 조회합니다. "
         "client를 외부에서 전달받아 객체 생성 오버헤드를 최소화합니다."),
    sp(4),
    code_block([
        ("async function fetchOnePair(client, pairAddress, blockNumber?) {", False),
        ("  const results = await client.multicall({", False),
        ("    allowFailure: true,", False),
        ("    ...(blockNumber !== undefined ? { blockNumber } : {}),", False),
        ("    contracts: [", False),
        ("      // ERC-20 기본 정보", True),
        ("      { abi: PAIR_ABI, functionName: 'name' },             // [0]  토큰 이름", True),
        ("      { abi: PAIR_ABI, functionName: 'symbol' },           // [1]  토큰 심볼", True),
        ("      { abi: PAIR_ABI, functionName: 'decimals' },         // [2]  소수점 자리 (보통 18)", True),
        ("      { abi: PAIR_ABI, functionName: 'totalSupply' },      // [3]  총 LP 토큰 공급량", True),
        ("      // 풀 구성", True),
        ("      { abi: PAIR_ABI, functionName: 'getTokens' },        // [4]  [token0, token1]", True),
        ("      { abi: PAIR_ABI, functionName: 'getFactory' },       // [5]  Factory 주소", True),
        ("      { abi: PAIR_ABI, functionName: 'getReserves' },      // [6]  [reserve0, reserve1]", True),
        ("      { abi: PAIR_ABI, functionName: 'getVirtualReserves' }, // [7]  가상 준비금 (spread용)", True),
        ("      // 수수료", True),
        ("      { abi: PAIR_ABI, functionName: 'getFeesBps' },       // [8]  [feeLp, feePool, burnFee]", True),
        ("      { abi: PAIR_ABI, functionName: 'getLoanFeesBps' },   // [9]  [loanFee0, loanFee1]", True),
        ("      { abi: PAIR_ABI, functionName: 'getFeeCollector' },  // [10] 수수료 수취 주소", True),
        ("      // 이자율 모델", True),
        ("      { abi: PAIR_ABI, functionName: 'getInterestParamsBps' },       // [11] [token0IRM, token1IRM]", True),
        ("      { abi: PAIR_ABI, functionName: 'getInterestMultiplier0' },     // [12] token0 이자 승수 (RAY)", True),
        ("      { abi: PAIR_ABI, functionName: 'getInterestMultiplier1' },     // [13] token1 이자 승수 (RAY)", True),
        ("      { abi: PAIR_ABI, functionName: 'calcVariableInterestRate0' },  // [14] token0 변동금리 (RAY)", True),
        ("      { abi: PAIR_ABI, functionName: 'calcVariableInterestRate1' },  // [15] token1 변동금리 (RAY)", True),
        ("      { abi: PAIR_ABI, functionName: 'getLastYieldAccumulator' },    // [16] [yieldAcc0, yieldAcc1]", True),
        ("      // 대출 상태", True),
        ("      { abi: PAIR_ABI, functionName: 'getTotalBorrowed0' },          // [17] token0 총 미상환 대출", True),
        ("      { abi: PAIR_ABI, functionName: 'getTotalBorrowed1' },          // [18] token1 총 미상환 대출", True),
        ("      { abi: PAIR_ABI, functionName: 'getAccumulatedPoolFees' },     // [19] [fee0, fee1] 미배분", True),
        ("      { abi: PAIR_ABI, functionName: 'getLastUpdateTimestamp' },     // [20] Unix 타임스탬프", True),
        ("      { abi: PAIR_ABI, functionName: 'getNextLoanId' },              // [21] 다음 대출 ID", True),
        ("      // 리스크 파라미터 (Factory 기본값에서 개별 오버라이드 가능)", True),
        ("      { abi: PAIR_ABI, functionName: 'getBorrowLimitBps' },          // [22]", True),
        ("      { abi: PAIR_ABI, functionName: 'getLiquidationPenaltyBps' },   // [23]", True),
        ("      { abi: PAIR_ABI, functionName: 'getMaxBorrowPerTickAndRange' }, // [24]", True),
        ("      { abi: PAIR_ABI, functionName: 'getPriceDecay' },              // [25]", True),
        ("      { abi: PAIR_ABI, functionName: 'getSwapPriceToleranceBps' },   // [26]", True),
        ("      { abi: PAIR_ABI, functionName: 'getTickBuffer' },              // [27]", True),
        ("      // 상수", True),
        ("      { abi: PAIR_ABI, functionName: 'MINIMUM_LIQUIDITY' },          // [28]", True),
        ("      { abi: PAIR_ABI, functionName: 'INTEREST_MULTIPLIER_DECIMALS' }, // [29]", True),
        ("      { abi: PAIR_ABI, functionName: 'RAY_DECIMALS' }                // [30] = 27", True),
        ("    ]", False),
        ("  });", False),
        ("  // ... 결과 파싱 후 PairData 반환", True),
        ("  // token0Symbol·Decimals는 fetchAllPairs Step3에서 채워짐", True),
        ("  return { address: pairAddress, name, symbol, ...",False),
        ("    token0Symbol: '', token0Decimals: 18,", False),
        ("    token1Symbol: '', token1Decimals: 18 };", False),
        ("}", False),
    ]),
    sp(6),
    h2("5.2 fetchAllPairs() — 모든 Pair 4단계 처리"),
    code_block([
        ("export async function fetchAllPairs(", False),
        ("  config: ChainConfig,", False),
        ("  factoryAddress: `0x${string}`,", False),
        ("  allPairsLength: bigint,  // fetchFactoryData에서 받아온 총 Pair 수", True),
        ("  blockNumber?: bigint", False),
        ("): Promise<PairData[]> {", False),
        ("  const client = createPublicClient({...});", False),
        ("  const length = Number(allPairsLength);", False),
        ("  if (length === 0) return [];", False),
        ("", False),
        ("  // Step 1: Factory.getPairAtIndex(i) 일괄 호출 -> Pair 주소 배열", True),
        ("  const indexResults = await client.multicall({", False),
        ("    allowFailure: true,", False),
        ("    contracts: Array.from({ length }, (_, i) => ({", False),
        ("      address: factoryAddress, abi: FACTORY_ABI,", False),
        ("      functionName: 'getPairAtIndex', args: [BigInt(i)]", False),
        ("    }))", False),
        ("  });", False),
        ("  const pairAddresses = indexResults", False),
        ("    .filter(r => r.status === 'success')", False),
        ("    .map(r => r.result as `0x${string}`);", False),
        ("", False),
        ("  // Step 2: 각 Pair에 대해 fetchOnePair 병렬 실행", True),
        ("  //   Promise.all: 모든 Pair를 동시 처리 -> 가장 느린 Pair가 전체 대기시간 결정", True),
        ("  const pairs = await Promise.all(", False),
        ("    pairAddresses.map(addr => fetchOnePair(client, addr, blockNumber))", False),
        ("  );", False),
        ("", False),
        ("  // Step 3: 중복 제거 후 토큰 symbol·decimals를 단일 multicall로 조회", True),
        ("  //   Set: 중복 제거 -> 같은 토큰이 여러 Pair에 있어도 1회만 조회", True),
        ("  //   인덱스 규칙: 토큰 i의 symbol = i*2, decimals = i*2+1", True),
        ("  const uniqueTokens = [...new Set(pairs.flatMap(p => [p.token0, p.token1]))];", False),
        ("  const metaResults = await client.multicall({", False),
        ("    allowFailure: true,", False),
        ("    contracts: uniqueTokens.flatMap(token => [", False),
        ("      { address: token, abi: ERC20_META_ABI, functionName: 'symbol' },   // i*2", True),
        ("      { address: token, abi: ERC20_META_ABI, functionName: 'decimals' }  // i*2+1", True),
        ("    ])", False),
        ("  });", False),
        ("  const tokenMeta = new Map<string, {symbol:string; decimals:number}>();", False),
        ("  uniqueTokens.forEach((token, i) => {", False),
        ("    tokenMeta.set(token, {", False),
        ("      symbol:   metaResults[i*2].status   === 'success' ? metaResults[i*2].result   : '',", False),
        ("      decimals: metaResults[i*2+1].status === 'success' ? metaResults[i*2+1].result : 18", False),
        ("    });", False),
        ("  });", False),
        ("", False),
        ("  // Step 4: Pair에 토큰 메타데이터 주입 후 반환", True),
        ("  //   스프레드(...p): 기존 Pair 데이터 복사 후 4개 필드만 덮어씀", True),
        ("  return pairs.map(p => ({", False),
        ("    ...p,", False),
        ("    token0Symbol:   tokenMeta.get(p.token0)?.symbol   ?? '',", False),
        ("    token0Decimals: tokenMeta.get(p.token0)?.decimals ?? 18,", False),
        ("    token1Symbol:   tokenMeta.get(p.token1)?.symbol   ?? '',", False),
        ("    token1Decimals: tokenMeta.get(p.token1)?.decimals ?? 18,", False),
        ("  }));", False),
        ("}", False),
    ]),
    sp(4),
    h2("5.3 표시 유틸 함수"),
    code_block([
        ("// Unix 타임스탬프(초) -> 로컬 날짜시간 문자열", True),
        ("// * 1000: JS Date는 밀리초 단위, 블록체인 타임스탬프는 초 단위", True),
        ("export function formatTimestamp(ts: bigint): string {", False),
        ("  if (ts === 0n) return '-';", False),
        ("  return new Date(Number(ts) * 1000).toLocaleString();", False),
        ("}", False),
        ("", False),
        ("// 원시 BigInt -> 소수점 있는 문자열", True),
        ("// e.g. formatAmount(1000000n, 6) -> '1.000000'  (1 USDC: 6 decimals)", True),
        ("export function formatAmount(value: bigint, decimals: number): string {", False),
        ("  return formatUnits(value, decimals);  // viem 내장 유틸", True),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 6. fetchVault.ts ───────────────────────────────────────────────────────────
story += [
    h1("6. src/config/fetchVault.ts — Vault 데이터 조회"),
    body("Vault 컨트랙트는 Pair 풀의 유휴 자금을 Aave에 예치하여 추가 수익을 창출합니다. "
         "Vault 기본 정보와 각 토큰별 상태를 2단계 multicall로 조회합니다."),
    sp(4),
    h2("6.1 fetchVaultData() — Vault 전체 데이터 조회"),
    code_block([
        ("export async function fetchVaultData(", False),
        ("  config: ChainConfig,", False),
        ("  vaultAddress: `0x${string}`,    // fetchFactoryData의 data.vault 주소", True),
        ("  tokenAddresses: `0x${string}`[], // 모든 Pair의 token0·token1 (중복 제거됨)", True),
        ("  blockNumber?: bigint", False),
        ("): Promise<VaultData> {", False),
        ("  const client = createPublicClient({...});", False),
        ("  const blockOpt = blockNumber !== undefined ? { blockNumber } : {};", False),
        ("", False),
        ("  // Step 1: Vault 기본 정보 (토큰 무관 - 2개 함수)", True),
        ("  const baseResults = await client.multicall({", False),
        ("    allowFailure: true, ...blockOpt,", False),
        ("    contracts: [", False),
        ("      { address: vaultAddress, abi: VAULT_ABI,", False),
        ("        functionName: 'getFactory' },   // [0] Factory 주소", True),
        ("      { address: vaultAddress, abi: VAULT_ABI,", False),
        ("        functionName: 'getAavePool' }   // [1] Aave 풀 주소", True),
        ("    ]", False),
        ("  });", False),
        ("", False),
        ("  // Step 2: 토큰별 4개 함수 x n토큰 -> 단일 multicall", True),
        ("  //   인덱스 규칙: 토큰 i의 j번 함수 -> i*4 + j", True),
        ("  const tokenContracts = tokenAddresses.flatMap(token => [", False),
        ("    { address: vaultAddress, abi: VAULT_ABI,", False),
        ("      functionName: 'getAssetData',        args: [token] }, // i*4+0", True),
        ("    { address: vaultAddress, abi: VAULT_ABI,", False),
        ("      functionName: 'getAssetStatus',       args: [token] }, // i*4+1 true=Vault보관 false=Aave예치", True),
        ("    { address: vaultAddress, abi: VAULT_ABI,", False),
        ("      functionName: 'getAaveTokenSupport', args: [token] }, // i*4+2", True),
        ("    { address: vaultAddress, abi: VAULT_ABI,", False),
        ("      functionName: 'getYieldAccumulator', args: [token] }  // i*4+3 이자 누적 승수(RAY)", True),
        ("  ]);", False),
        ("  const tokenResults = await client.multicall({", False),
        ("    allowFailure: true, ...blockOpt, contracts: tokenContracts", False),
        ("  });", False),
        ("", False),
        ("  // Step 3: 결과 파싱 - 각 토큰의 base offset = i*4", True),
        ("  const tokens: VaultTokenData[] = tokenAddresses.map((token, i) => {", False),
        ("    const base = i * 4;", False),
        ("    function getToken<T>(offset: number, fallback: T): T {", False),
        ("      const r = tokenResults[base + offset];", False),
        ("      return r.status === 'success' ? r.result as T : fallback;", False),
        ("    }", False),
        ("    return {", False),
        ("      token,", False),
        ("      assetData:        getToken<AssetData>(0, ASSET_FALLBACK),", False),
        ("      isIdle:           getToken<boolean>(1, false),", False),
        ("      aaveSupport:      getToken<AaveTokenSupport>(2, AAVE_FALLBACK),", False),
        ("      yieldAccumulator: getToken<bigint>(3, 0n)", False),
        ("    };", False),
        ("  });", False),
        ("", False),
        ("  return {", False),
        ("    address: vaultAddress,", False),
        ("    factory:  getBase<`0x${string}`>(0, ZERO),", False),
        ("    aavePool: getBase<`0x${string}`>(1, ZERO),", False),
        ("    tokens", False),
        ("  };", False),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 7. +page.svelte ────────────────────────────────────────────────────────────
story += [
    h1("7. src/routes/+page.svelte — 메인 페이지 핵심 함수"),
    body("앱의 중심 파일. 3개 체인의 상태를 $state로 관리하고, "
         "fetch 함수들을 조율하여 데이터를 로드한 뒤 카드 컴포넌트로 전달합니다."),
    sp(4),
    h2("7.1 ChainState 타입 & $state 초기화"),
    code_block([
        ("type ChainState = {", False),
        ("  factory: FactoryData | null;", False),
        ("  pairs: PairData[];", False),
        ("  vault: VaultData | null;", False),
        ("  loading: boolean;              // 로딩 스피너 표시 여부", True),
        ("  error: string | null;", False),
        ("  loadedAt: Date | null;", False),
        ("  factoryHistory: FactoryData[]; // 7일치 Factory 스냅샷 (스파크라인용)", True),
        ("  pairHistory: Record<string, PairData[]> | null; // 주소별 7일치 Pair 스냅샷", True),
        ("  historyLoading: boolean;", False),
        ("  historyError: string | null;", False),
        ("};", False),
        ("", False),
        ("// $state: Svelte 5 Runes 반응형 변수 - 값 변경 시 UI 자동 재렌더", True),
        ("let states = $state<Record<ChainKey, ChainState>>(", False),
        ("  Object.fromEntries(", False),
        ("    Object.keys(CHAINS).map(k => [k, {", False),
        ("      factory: null, pairs: [], vault: null,", False),
        ("      loading: false, error: null, loadedAt: null,", False),
        ("      factoryHistory: [], pairHistory: null,", False),
        ("      historyLoading: false, historyError: null", False),
        ("    }])", False),
        ("  ) as unknown as Record<ChainKey, ChainState>", False),
        (");", False),
    ]),
    sp(6),
    h2("7.2 loadChain() — 단일 체인 데이터 로드"),
    body("Factory -> Pairs -> Vault 순서로 순차 조회하되, 각 단계 완료 즉시 UI에 반영합니다."),
    sp(4),
    code_block([
        ("async function loadChain(key: ChainKey) {", False),
        ("  const config = CHAINS[key];", False),
        ("  states[key].loading = true;  // 로딩 스피너 즉시 표시", True),
        ("  states[key].error = null;", False),
        ("  try {", False),
        ("    // Step 1: Factory (13개 함수 multicall)", True),
        ("    const factory = await fetchFactoryData(config);", False),
        ("    states[key].factory = factory;  // -> FactoryCard 즉시 표시", True),
        ("    sidebarStore.setFactory(key, config.name, config.factory);", False),
        ("", False),
        ("    // Step 2: Pair 목록 (factory.allPairsLength 재활용)", True),
        ("    const pairs = await fetchAllPairs(config, config.factory, factory.allPairsLength);", False),
        ("    states[key].pairs = pairs;      // -> PairCard 목록 즉시 표시", True),
        ("    sidebarStore.setPairsForChain(key, config.name, pairs);", False),
        ("", False),
        ("    // Step 3: Vault (토큰 주소 수집 후 조회)", True),
        ("    //   flatMap: 각 Pair에서 token0·token1 추출 -> 1차원 배열로 평탄화", True),
        ("    //   Set: 중복 제거 -> 같은 토큰을 1회만 Vault에 조회", True),
        ("    const allTokens = pairs.flatMap(p => [p.token0, p.token1]);", False),
        ("    const uniqueTokens = [...new Set(allTokens)] as `0x${string}`[];", False),
        ("    const vault = await fetchVaultData(config, factory.vault, uniqueTokens);", False),
        ("    states[key].vault = vault;      // -> VaultCard 즉시 표시", True),
        ("    sidebarStore.setVault(key, config.name, vault.address);", False),
        ("", False),
        ("  } catch (e) {", False),
        ("    states[key].error = e instanceof Error ? e.message : 'Unknown error';", False),
        ("  } finally {", False),
        ("    states[key].loading = false;    // 성공·실패 무관 로딩 종료", True),
        ("    states[key].loadedAt = new Date();", False),
        ("  }", False),
        ("}", False),
    ]),
    sp(6),
    h2("7.3 loadAll() — 3개 체인 병렬 로드"),
    code_block([
        ("// Promise.all: 3개 체인을 동시에 로드 -> 순차 실행 대비 ~3배 빠름", True),
        ("function loadAll() {", False),
        ("  return Promise.all((Object.keys(CHAINS) as ChainKey[]).map(loadChain));", False),
        ("}", False),
    ]),
    sp(6),
    h2("7.4 loadHistory() — 7일치 히스토리 로드"),
    body("DeFiLlama API로 7일치 블록번호를 조회한 뒤, "
         "각 블록에서 Factory·Pair 상태를 순차 조회하여 스파크라인 데이터를 구성합니다."),
    sp(4),
    code_block([
        ("async function loadHistory(key: ChainKey) {", False),
        ("  states[key].historyLoading = true;", False),
        ("  try {", False),
        ("    const config = CHAINS[key];", False),
        ("", False),
        ("    // 오늘 UTC 자정부터 6일 전까지 7개 날짜 생성", True),
        ("    // i=0 -> 6일 전, i=6 -> 오늘 (스파크라인 좌=과거, 우=현재)", True),
        ("    const nowMs = Date.now();", False),
        ("    const todayMidnightMs = nowMs - (nowMs % 86_400_000);", False),
        ("    const dates = Array.from({ length: 7 }, (_, i) =>", False),
        ("      new Date(todayMidnightMs - (6 - i) * 86_400_000)", False),
        ("    );", False),
        ("", False),
        ("    // DeFiLlama API로 각 날짜의 블록번호 병렬 조회", True),
        ("    const blocks = await Promise.all(dates.map(d => dateToBlock(key, d)));", False),
        ("", False),
        ("    // 각 블록 시점 Factory·Pair 데이터 순차 조회 (병렬 시 RPC 과부하 우려)", True),
        ("    const snapshots = [];", False),
        ("    for (const block of blocks) {", False),
        ("      const factory = await fetchFactoryData(config, block);", False),
        ("      const pairs = await fetchAllPairs(", False),
        ("        config, config.factory, factory.allPairsLength, block);", False),
        ("      snapshots.push({ factory, pairs });", False),
        ("    }", False),
        ("", False),
        ("    // Factory 히스토리: [day0, day1, ..., day6] 시간순 배열", True),
        ("    states[key].factoryHistory = snapshots.map(s => s.factory);", False),
        ("", False),
        ("    // Pair 히스토리: { '0xPairAddr': [day0Data, ..., day6Data] }", True),
        ("    const byAddr: Record<string, PairData[]> = {};", False),
        ("    for (const { pairs } of snapshots) {", False),
        ("      for (const pair of pairs) {", False),
        ("        if (!byAddr[pair.address]) byAddr[pair.address] = [];", False),
        ("        byAddr[pair.address].push(pair);", False),
        ("      }", False),
        ("    }", False),
        ("    states[key].pairHistory = byAddr;", False),
        ("", False),
        ("  } catch (e) { ... }", False),
        ("  finally { states[key].historyLoading = false; }", False),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 7.5~7.7 ────────────────────────────────────────────────────────────────────
story += [
    h2("7.5 dateToBlock() — 날짜 -> 블록번호 변환"),
    body("DeFiLlama의 block API를 통해 특정 날짜·시각에 해당하는 블록번호를 조회합니다."),
    sp(4),
    code_block([
        ("async function dateToBlock(chainKey: ChainKey, date: Date): Promise<bigint> {", False),
        ("  const ts = Math.floor(date.getTime() / 1000);  // JS(ms) -> Unix(s)", True),
        ("  const res = await fetch(", False),
        ("    `https://coins.llama.fi/block/${DEFILLAMA_SLUG[chainKey]}/${ts}`", False),
        ("  );", False),
        ("  if (!res.ok) throw new Error(`Block lookup failed`);", False),
        ("  const json = await res.json() as { height: number };", False),
        ("  return BigInt(json.height);", False),
        ("}", False),
    ]),
    sp(6),
    h2("7.6 compareAllRange() — 날짜 범위 비교"),
    code_block([
        ("async function compareAllRange() {", False),
        ("  if (!fromDate || !toDate) { rangeError = '...'; return; }", False),
        ("  const from = new Date(fromDate);", False),
        ("  const to   = new Date(toDate);", False),
        ("  if (from >= to) { rangeError = '...'; return; }", False),
        ("", False),
        ("  // 3개 체인의 To 블록번호 병렬 조회", True),
        ("  const keys = Object.keys(CHAINS) as ChainKey[];", False),
        ("  const blockPairs = await Promise.all(", False),
        ("    keys.map(async key => {", False),
        ("      const toBlock = await dateToBlock(key, to);", False),
        ("      return { key, toBlock };", False),
        ("    })", False),
        ("  );", False),
        ("", False),
        ("  // 각 체인에 대해 To 시점 데이터 병렬 로드", True),
        ("  await Promise.all(", False),
        ("    blockPairs.map(({ key, toBlock }) => compareChainRange(key, toBlock, to))", False),
        ("  );", False),
        ("}", False),
    ]),
    sp(6),
    h2("7.7 검색 필터 함수"),
    body("normalizedQuery ($derived)를 참조해 Pair 목록을 실시간으로 필터링합니다. "
         "체인 수준 주소가 일치하면 해당 체인의 모든 카드를 표시합니다."),
    sp(4),
    code_block([
        ("// $derived: searchQuery 변경 시 자동 재계산되는 파생 값", True),
        ("const normalizedQuery = $derived(searchQuery.trim().toLowerCase());", False),
        ("", False),
        ("// 체인 수준 주소(Factory·Vault·aavePool 등)가 쿼리와 일치하는지 검사", True),
        ("function matchesChainAddrs(query, chainFactoryAddr, factory, vault): boolean {", False),
        ("  const addrs = [", False),
        ("    chainFactoryAddr, factory?.feeCollector, factory?.beaconAddress,", False),
        ("    factory?.vault, factory?.aavePool, vault?.address, vault?.aavePool,", False),
        ("    ...(vault?.tokens.map(t => t.token) ?? [])", False),
        ("  ];", False),
        ("  return addrs.some(a => a?.toLowerCase().includes(query));", False),
        ("}", False),
        ("", False),
        ("// Pair 배열을 검색 쿼리로 필터링", True),
        ("function filterPairs(pairs, chainFactoryAddr, factory, vault): PairData[] {", False),
        ("  if (!normalizedQuery) return pairs;  // 쿼리 없음 -> 전체 반환", True),
        ("  if (matchesChainAddrs(normalizedQuery, ...)) return pairs; // 체인 주소 일치 -> 전체", True),
        ("  return pairs.filter(p =>", False),
        ("    p.symbol.toLowerCase().includes(normalizedQuery)   ||", False),
        ("    p.name.toLowerCase().includes(normalizedQuery)     ||", False),
        ("    p.token0.toLowerCase().includes(normalizedQuery)   ||", False),
        ("    p.token1.toLowerCase().includes(normalizedQuery)   ||", False),
        ("    p.address.toLowerCase().includes(normalizedQuery)  ||", False),
        ("    (p.token0Symbol?.toLowerCase() ?? '').includes(normalizedQuery) ||", False),
        ("    (p.token1Symbol?.toLowerCase() ?? '').includes(normalizedQuery) ||", False),
        ("    p.factory.toLowerCase().includes(normalizedQuery)", False),
        ("  );", False),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 8. editing.ts ───────────────────────────────────────────────────────────────
story += [
    h1("8. src/config/editing.ts — Safe 트랜잭션 빌드"),
    body("파라미터 편집 모달에서 입력된 값을 검증하고, "
         "Gnosis Safe 앱에서 가져올 수 있는 JSON 트랜잭션 배치 파일로 직렬화합니다."),
    sp(4),
    h2("8.1 parseEditValues() — 입력값 검증 & 파싱"),
    code_block([
        ("export function parseEditValues(", False),
        ("  fields: EditField[],", False),
        ("  rawValues: Record<string, string>  // 모달 입력 원시 문자열", True),
        (") {", False),
        ("  const parsed: Record<string, unknown> = {};", False),
        ("", False),
        ("  for (const field of fields) {", False),
        ("    const raw = rawValues[field.key]?.trim() ?? '';", False),
        ("    if (!raw) return { error: `${field.label} is required.`, values: parsed };", False),
        ("", False),
        ("    if (field.type === 'address') {", False),
        ("      if (!isAddress(raw)) return { error: '...valid address required', values: parsed };", False),
        ("      parsed[field.key] = raw as `0x${string}`; continue;", False),
        ("    }", False),
        ("    if (field.type === 'address[]') {", False),
        ("      // 공백·쉼표로 구분된 주소 목록 파싱", True),
        ("      const addresses = raw.split(/[\\s,]+/).map(a=>a.trim()).filter(Boolean);", False),
        ("      const invalid = addresses.find(a => !isAddress(a));", False),
        ("      if (invalid) return { error: `invalid: ${invalid}`, values: parsed };", False),
        ("      parsed[field.key] = addresses as `0x${string}`[]; continue;", False),
        ("    }", False),
        ("    if (field.type === 'bool') {", False),
        ("      const n = raw.toLowerCase();", False),
        ("      if (n !== 'true' && n !== 'false')", False),
        ("        return { error: 'must be true or false', values: parsed };", False),
        ("      parsed[field.key] = n === 'true'; continue;", False),
        ("    }", False),
        ("    // 정수형 (uint16 / uint32 / uint128 / int16)", True),
        ("    if (!/^-?\\d+$/.test(raw)) return { error: 'must be integer', values: parsed };", False),
        ("    const value = BigInt(raw);", False),
        ("    const limit = LIMITS[field.type]; // { min, max } 범위 검사", True),
        ("    if (value < limit.min || value > limit.max)", False),
        ("      return { error: `must be between ${limit.min}..${limit.max}`, values: parsed };", False),
        ("    parsed[field.key] = field.type === 'uint128' ? value : Number(value);", False),
        ("  }", False),
        ("  return { values: parsed };  // error 없음 -> 성공", True),
        ("}", False),
    ]),
    sp(6),
    h2("8.2 buildSafeTransaction() — Safe 트랜잭션 객체 생성"),
    code_block([
        ("export function buildSafeTransaction(", False),
        ("  draft: EditDraft, values: Record<string, unknown>", False),
        ("): SafeTransaction {", False),
        ("  const abi  = ABI_BY_KIND[draft.contractKind]; // factory/pair/vault ABI 선택", True),
        ("  const args = draft.buildArgs(values);          // EditDraft의 buildArgs 호출", True),
        ("  const method = abi.find(item =>", False),
        ("    item.type === 'function' && item.name === draft.functionName);", False),
        ("  const inputs = method?.type === 'function' ? method.inputs : [];", False),
        ("  return {", False),
        ("    to: draft.targetAddress,  // 컨트랙트 주소", True),
        ("    value: '0',               // ETH 전송 없음", True),
        ("    data: '',                 // Safe UI가 ABI encode 처리", True),
        ("    contractMethod: {", False),
        ("      contractName: CONTRACT_NAME_BY_KIND[draft.contractKind],", False),
        ("      inputs, name: draft.functionName,", False),
        ("      payable: method?.stateMutability === 'payable' ?? false", False),
        ("    },", False),
        ("    contractInputsValues: buildContractInputsValues(inputs, args)", False),
        ("  };", False),
        ("}", False),
    ]),
    sp(6),
    h2("8.3 buildSafeJson() — JSON 배치 파일 생성"),
    code_block([
        ("export function buildSafeJson(chainKey: ChainKey, transactions: SafeTransaction[]) {", False),
        ("  const safe = SAFE_BY_CHAIN[chainKey];  // 체인별 Safe 주소 조회", True),
        ("  return {", False),
        ("    chainId: safe.chainId,               // e.g. '42161' for Arbitrum", True),
        ("    createdAt: Date.now(),", False),
        ("    meta: {", False),
        ("      name: 'Transactions Batch',", False),
        ("      createdFromSafeAddress: safe.address", False),
        ("    },", False),
        ("    transactions  // SafeTransaction[] 배열", True),
        ("  };", False),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 9. sidebar.svelte.ts ────────────────────────────────────────────────────────
story += [
    h1("9. src/lib/sidebar.svelte.ts — 사이드바 상태 관리"),
    body("Factory·Vault·Pair 각각에 대한 선택(체크박스) 상태를 관리하는 Svelte 5 클래스 스토어입니다. "
         "선택된 항목이 있으면 메인 페이지에서 해당 항목만 필터링하여 표시합니다."),
    sp(4),
    code_block([
        ("class SidebarStore {", False),
        ("  // ── Pair ──────────────────────────────────────", True),
        ("  pairs = $state<PairEntry[]>([]);", False),
        ("  selectedAddresses = $state<Set<string>>(new Set());", False),
        ("", False),
        ("  // 체인의 Pair 목록 교체 (같은 체인 기존 항목 제거 후 삽입)", True),
        ("  setPairsForChain(chain, chainLabel, rawPairs) {", False),
        ("    const kept  = this.pairs.filter(p => p.chain !== chain);", False),
        ("    const added = rawPairs.map(p => ({", False),
        ("      address: p.address, symbol: p.symbol,", False),
        ("      token0Symbol: p.token0Symbol ?? p.token0.slice(0,6)+'...',", False),
        ("      token1Symbol: p.token1Symbol ?? p.token1.slice(0,6)+'...',", False),
        ("      chain, chainLabel", False),
        ("    }));", False),
        ("    this.pairs = [...kept, ...added];", False),
        ("  }", False),
        ("", False),
        ("  // 토글: 선택됐으면 해제, 아니면 추가", True),
        ("  togglePair(address: string) {", False),
        ("    const next = new Set(this.selectedAddresses);", False),
        ("    if (next.has(address)) next.delete(address);", False),
        ("    else next.add(address);", False),
        ("    this.selectedAddresses = next; // 새 Set 할당으로 Svelte 반응성 트리거", True),
        ("  }", False),
        ("", False),
        ("  isSelected(address: string): boolean {", False),
        ("    return this.selectedAddresses.has(address);", False),
        ("  }", False),
        ("  get selectedCount(): number { return this.selectedAddresses.size; }", False),
        ("", False),
        ("  // Factory, Vault도 동일한 패턴으로 구현", True),
        ("  // setFactory / toggleFactory / isFactorySelected / selectedFactoryCount", True),
        ("  // setVault   / toggleVault   / isVaultSelected   / selectedVaultCount", True),
        ("}", False),
        ("", False),
        ("export const sidebarStore = new SidebarStore(); // 싱글톤 - 앱 전체 공유", True),
    ]),
    PageBreak(),
]

# ── 10. 컴포넌트 핵심 함수 ──────────────────────────────────────────────────────
story += [
    h1("10. 컴포넌트 핵심 함수"),
    h2("10.1 FactoryCard.svelte — diff 배지 & 편집 함수"),
    code_block([
        ("// nd(): bps 정수 두 값의 차이를 '▲ +30 bps' 형식 문자열로 반환", True),
        ("// 변화 없으면 null -> {#if lbl}로 배지 숨김", True),
        ("function nd(curr: number, prev: number): string | null {", False),
        ("  const d = curr - prev;", False),
        ("  if (d === 0) return null;", False),
        ("  return d > 0 ? `up +${d} bps` : `down ${d} bps`;", False),
        ("}", False),
        ("", False),
        ("// nd_dir(): diff 방향 -> CSS 클래스 .diff.up(초록) / .diff.down(빨강) 결정", True),
        ("function nd_dir(curr: number, prev: number): 'up' | 'down' | null {", False),
        ("  if (curr === prev) return null;", False),
        ("  return curr > prev ? 'up' : 'down';", False),
        ("}", False),
        ("", False),
        ("// copy(): 클립보드 복사 후 1초간 '✓ Copied' 피드백 표시", True),
        ("function copy(key: string, text: string) {", False),
        ("  navigator.clipboard.writeText(text);", False),
        ("  copied = key;", False),
        ("  setTimeout(() => (copied = null), 1000);", False),
        ("}", False),
        ("", False),
        ("// copyAll(): 전체 데이터를 human-readable JSON으로 복사", True),
        ("// bigint -> .toString()  /  bps number -> bpsToPercent()", True),
        ("function copyAll() {", False),
        ("  if (!data) return;", False),
        ("  const readable = {", False),
        ("    feeCollector: data.feeCollector,", False),
        ("    fees: { feeLp: bpsToPercent(data.fees.feeLp), ... },", False),
        ("    priceDecay: data.priceDecay.toString(), // bigint -> string", True),
        ("    ...etc", False),
        ("  };", False),
        ("  navigator.clipboard.writeText(JSON.stringify(readable, null, 2));", False),
        ("  copied = '__all__';", False),
        ("  setTimeout(() => (copied = null), 1000);", False),
        ("}", False),
        ("", False),
        ("// editFactory(): 편집 모달 열기 - EditDraft 구성 후 onEdit 콜백 호출", True),
        ("function editFactory(title, functionName, fields, buildArgs) {", False),
        ("  if (!data || !chainKey || !factoryAddress || !onEdit) return;", False),
        ("  onEdit({", False),
        ("    chainKey, chainName: chainLabel,", False),
        ("    targetLabel: 'Factory', targetAddress: factoryAddress,", False),
        ("    contractKind: 'factory', // ABI_BY_KIND['factory'] = UniPoolFactoryAbi", True),
        ("    functionName, title, fields, buildArgs", False),
        ("  });", False),
        ("}", False),
    ]),
    sp(6),
    h2("10.2 PairCard.svelte — 3가지 diff 함수"),
    code_block([
        ("// nd(): bps 정수 diff", True),
        ("function nd(curr: number, prev: number) {", False),
        ("  if (curr === prev) return null;", False),
        ("  const d = curr - prev;", False),
        ("  return { label: d>0 ? `up +${d} bps` : `down ${d} bps`,", False),
        ("           dir: d > 0 ? 'up' : 'down' };", False),
        ("}", False),
        ("", False),
        ("// bd(): bigint diff - reserve0 / totalSupply 등 큰 정수 값", True),
        ("// decimals 전달 시 formatAmount()로 소수점 표시", True),
        ("// Math.abs는 bigint 미지원 -> 수동 절댓값: d < 0n ? -d : d", True),
        ("function bd(curr: bigint, prev: bigint, decimals?: number) {", False),
        ("  if (curr === prev) return null;", False),
        ("  const d   = curr - prev;", False),
        ("  const abs = d < 0n ? -d : d;", False),
        ("  const fmt = decimals !== undefined ? formatAmount(abs, decimals) : abs.toString();", False),
        ("  return { label: d>0n ? `up +${fmt}` : `down -${fmt}`,", False),
        ("           dir: d > 0n ? 'up' : 'down' };", False),
        ("}", False),
        ("", False),
        ("// rd(): RAY(10^27) 단위 bigint diff - 이자율·이자 승수", True),
        ("// isRate=true  -> % 표시  e.g. 'up +0.0300%'", True),
        ("// isRate=false -> x 표시  e.g. 'up +0.000035x'", True),
        ("function rd(curr: bigint, prev: bigint, isRate = false) {", False),
        ("  if (curr === prev) return null;", False),
        ("  const d      = curr - prev;", False),
        ("  const absNum = Math.abs(Number(d)) / 1e27;  // RAY -> 실수", True),
        ("  const fmt    = isRate", False),
        ("    ? (absNum * 100).toFixed(4) + '%'", False),
        ("    : absNum.toFixed(6) + 'x';", False),
        ("  return { label: d>0n ? `up +${fmt}` : `down -${fmt}`,", False),
        ("           dir: d > 0n ? 'up' : 'down' };", False),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 10.3 Sparkline + Sidebar ────────────────────────────────────────────────────
story += [
    h2("10.3 Sparkline.svelte — SVG 스파크라인"),
    body("외부 라이브러리 없이 순수 SVG로 구현된 미니 라인 차트. "
         "7일치 수치 배열을 받아 좌(과거)→우(현재) 방향으로 그립니다."),
    sp(4),
    code_block([
        ("// $derived로 선언 -> values/width/height 변경 시 자동 재계산", True),
        ("function buildChart(vals: number[], w: number, h: number) {", False),
        ("  const W = w - pad * 2;  // 실제 차트 폭 (여백 제외)", True),
        ("  const H = h - pad * 2;  // 실제 차트 높이", True),
        ("  if (vals.length < 2)", False),
        ("    return { polyline: '', area: '', lx: pad+W, ly: pad+H/2 };", False),
        ("", False),
        ("  const min = Math.min(...vals);", False),
        ("  const max = Math.max(...vals);", False),
        ("  const rng = max - min || 1;  // 모든 값이 같을 때 0나눔 방지", True),
        ("", False),
        ("  // 각 포인트 -> SVG 좌표 (x, y) 변환", True),
        ("  // x: 왼쪽(오래된 값) -> 오른쪽(최신 값)", True),
        ("  // y: SVG y축은 아래로 증가 -> 반전시켜 위=큰값", True),
        ("  const pts = vals.map((v, i) => {", False),
        ("    const x = pad + (i / (vals.length - 1)) * W;", False),
        ("    const y = pad + H - ((v - min) / rng) * H;  // 정규화 후 반전", True),
        ("    return `${x.toFixed(1)},${y.toFixed(1)}`;", False),
        ("  });", False),
        ("", False),
        ("  const polyline = pts.join(' ');", False),
        ("  const [lx, ly] = pts[pts.length-1].split(',').map(Number); // 최신값 점", True),
        ("  // 그라디언트 채움 영역: '왼쪽하단 -> 라인 -> 오른쪽하단' 폴리곤", True),
        ("  const area = `${pad},${pad+H} ${polyline} ${(pad+W).toFixed(1)},${pad+H}`;", False),
        ("  return { polyline, area, lx, ly };", False),
        ("}", False),
        ("const chart = $derived(buildChart(values, width, height));", False),
    ]),
    sp(6),
    h2("10.4 PairCard — 스파크라인 hover 함수"),
    code_block([
        ("// 스파크라인 대상 행에 마우스 진입 시 호출", True),
        ("// field: 행 식별 키  title: 툴팁 제목", True),
        ("// getter: PairData -> number 함수 (히스토리에서 수치 추출)", True),
        ("function enterSpark(field, title, getter, e: MouseEvent) {", False),
        ("  if (history.length < 2) return;  // 데이터 부족 시 무시", True),
        ("  hoveredField = field;", False),
        ("  sparkTitle   = title;", False),
        ("  sparkVals    = history.map(getter);  // 7일치 PairData -> number[]", True),
        ("  tipX = e.clientX + 16;  // 툴팁 X: 마우스 우측", True),
        ("  tipY = e.clientY - 60;  // 툴팁 Y: 마우스 위", True),
        ("}", False),
        ("function leaveSpark() {", False),
        ("  hoveredField = null;", False),
        ("  sparkVals    = [];", False),
        ("}", False),
    ]),
    sp(6),
    h2("10.5 Sidebar.svelte — 핵심 함수"),
    code_block([
        ("// 42자 이더리움 주소 -> '0x1234...abcd' 단축 형식", True),
        ("function shortAddr(addr: string) {", False),
        ("  return addr.slice(0, 6) + '...' + addr.slice(-4);", False),
        ("}", False),
        ("", False),
        ("// 섹션별 선택 초기화", True),
        ("function clearAll(section: 'factory' | 'vault' | 'pair') {", False),
        ("  if (section === 'factory') sidebarStore.clearFactories();", False),
        ("  else if (section === 'vault') sidebarStore.clearVaults();", False),
        ("  else sidebarStore.clearPairs();", False),
        ("}", False),
        ("", False),
        ("// $derived: sidebarStore.pairs 변경 시 자동 재정렬", True),
        ("const sortedPairs = $derived(", False),
        ("  [...sidebarStore.pairs].sort((a, b) =>", False),
        ("    (a.token0Symbol + a.token1Symbol)", False),
        ("      .localeCompare(b.token0Symbol + b.token1Symbol))", False),
        (");", False),
    ]),
    PageBreak(),
]

# ── 11. Safe 편집 흐름 ──────────────────────────────────────────────────────────
story += [
    h1("11. Safe 트랜잭션 편집 흐름 (+page.svelte)"),
    body("카드의 ✎ 아이콘 클릭부터 JSON 파일 다운로드까지의 전체 흐름입니다."),
    sp(4),
    code_block([
        ("// 1. 편집 모달 열기 - FactoryCard/PairCard/VaultCard의 onEdit 콜백에서 호출", True),
        ("function openEdit(draft: EditDraft) {", False),
        ("  activeEdit = draft;  // 편집 중인 대상 설정 -> 모달 표시", True),
        ("  editValues = Object.fromEntries(", False),
        ("    draft.fields.map(field => [field.key, field.value])  // 기본값 초기화", True),
        ("  );", False),
        ("  editError = null;", False),
        ("}", False),
        ("", False),
        ("// 2. 검증 후 SafeTransaction으로 변환하여 배치에 추가", True),
        ("function addEditToBatch() {", False),
        ("  if (!activeEdit) return;", False),
        ("  const parsed = parseEditValues(activeEdit.fields, editValues); // 타입·범위 검증", True),
        ("  if (parsed.error) { editError = parsed.error; return; }        // 실패 -> 에러 표시", True),
        ("  const tx = buildSafeTransaction(activeEdit, parsed.values);    // Safe 트랜잭션 생성", True),
        ("  // 스프레드로 불변 업데이트 -> Svelte 반응성 트리거", True),
        ("  safeBatches[activeEdit.chainKey] = [...safeBatches[activeEdit.chainKey], tx];", False),
        ("  activeEdit = null;  // 모달 닫기", True),
        ("  editValues = {};", False),
        ("  editError = null;", False),
        ("}", False),
        ("", False),
        ("// 3. 배치에서 특정 트랜잭션 제거", True),
        ("function removeSafeTx(chainKey: ChainKey, index: number) {", False),
        ("  safeBatches[chainKey] = safeBatches[chainKey].filter((_, i) => i !== index);", False),
        ("}", False),
        ("", False),
        ("// 4. Safe JSON 파일 다운로드", True),
        ("function downloadSafeJson(chainKey: ChainKey) {", False),
        ("  const txs = safeBatches[chainKey];", False),
        ("  if (txs.length === 0) return;", False),
        ("  // buildSafeJson: chainId + meta + transactions 배열을 Safe 형식으로 묶음", True),
        ("  const blob = new Blob(", False),
        ("    [JSON.stringify(buildSafeJson(chainKey, txs), null, 2)],", False),
        ("    { type: 'application/json' }", False),
        ("  );", False),
        ("  const url = URL.createObjectURL(blob); // Blob -> 임시 URL 생성", True),
        ("  const a = document.createElement('a');", False),
        ("  a.href = url;", False),
        ("  a.download = `unipool-${chainKey}-safe-transactions.json`;", False),
        ("  a.click();                    // 프로그래매틱 다운로드 트리거", True),
        ("  URL.revokeObjectURL(url);     // 메모리 해제", True),
        ("}", False),
    ]),
    PageBreak(),
]

# ── 12. 데이터 흐름 요약 ────────────────────────────────────────────────────────
story += [
    h1("12. 데이터 흐름 요약"),
    body("버튼 클릭 후 화면에 카드가 나타나기까지의 전체 데이터 이동 경로입니다."),
    sp(4),
    make_table([
        ["출발", "경유", "도착", "비고"],
        ["Load all chains\n버튼 클릭",
         "loadAll()\n-> Promise.all",
         "loadChain(arb)\nloadChain(base)\nloadChain(bsc)",
         "3개 체인 동시 병렬"],
        ["loadChain(key)",
         "fetchFactoryData\n-> viem multicall",
         "states[key].factory\n= FactoryData",
         "13개 함수 1회 RPC"],
        ["loadChain(key)",
         "fetchAllPairs\n-> getPairAtIndex x N\n-> fetchOnePair x N\n-> ERC20 symbol/dec",
         "states[key].pairs\n= PairData[]",
         "3단계 multicall"],
        ["loadChain(key)",
         "fetchVaultData\n-> 기본정보 2개\n-> 토큰별 x4 함수",
         "states[key].vault\n= VaultData",
         "2단계 multicall"],
        ["states[key].factory\n변경 ($state)",
         "Svelte 반응성\n자동 재렌더",
         "FactoryCard 표시",
         "즉시 반영"],
        ["states[key].pairs\n변경 ($state)",
         "filterPairs()\n($derived 활용)",
         "PairCard 목록\n표시",
         "검색 필터 적용"],
        ["✎ 클릭 -> openEdit",
         "parseEditValues\n-> buildSafeTransaction",
         "safeBatches[chain]\n-> JSON 다운로드",
         "Safe 트랜잭션"],
    ], [3.5*cm, 4.2*cm, 3.5*cm, W-11.2*cm]),
    PageBreak(),
]

# ── 13. 기술 개념 정리 ──────────────────────────────────────────────────────────
story += [
    h1("13. 주요 기술 개념 정리"),
    sp(4),
    make_table([
        ["개념", "설명"],
        ["Multicall",
         "여러 스마트 컨트랙트 함수를 하나의 HTTP 요청으로 묶는 기법. "
         "13개 개별 호출 -> 1회 요청으로 단축. viem의 client.multicall() 사용."],
        ["Archive Node",
         "모든 과거 블록의 상태를 저장하는 특수 RPC 노드. "
         "일반 노드는 최근 ~128 블록만 유지. 히스토리·날짜비교 기능에 필수."],
        ["BPS (Basis Points)",
         "1 bps = 0.01% = 1/10000. 정수로 수수료·비율을 표현하여 부동소수점 오류 방지. "
         "e.g. 30 bps = 0.30%,  8000 bps = 80.00%."],
        ["RAY (10^27)",
         "Solidity에서 비율을 정수로 표현하기 위한 정규화 단위. "
         "1 RAY = 1.0. 이자율·이자 승수 표현에 사용. "
         "JS 변환: Number(ray) / 1e27 * 100 -> 퍼센트."],
        ["Kinked IRM",
         "대출 활용도에 따라 이자율이 바뀌는 Interest Rate Model. "
         "optimalPoint 이하: 완만한 상승, 초과 시: 급격한 상승 -> 과도한 대출 억제."],
        ["Virtual Reserve",
         "UniPool 특유의 개념. 실제 잔액과 별도로 가격 계산에만 쓰이는 가상 잔액. "
         "매수(In)/매도(Out) 방향별로 분리 관리 -> 비대칭 가격(스프레드) 구현."],
        ["Beacon Proxy",
         "모든 Pair가 단일 Beacon 주소를 참조하는 업그레이드 패턴. "
         "Beacon 구현 주소 1회 변경으로 수백 개 Pair를 동시 업그레이드 가능."],
        ["Svelte 5 Runes",
         "$state: 반응형 변수 선언 - 값 변경 시 UI 자동 재렌더. "
         "$derived: 다른 상태에서 자동 계산되는 파생 값 (computed). "
         "Svelte 4 store 패턴보다 직관적."],
        ["Yield Accumulator",
         "Aave에서 발생한 이자를 LP들에게 공정하게 분배하기 위한 누적 승수(RAY). "
         "초기값 1 RAY, 이자 발생 시 증가. 수익률 = 현재값 / 예치 시점 값."],
        ["DeFiLlama Block API",
         "특정 날짜·시각(Unix 타임스탬프)을 체인별 블록번호로 변환하는 외부 API. "
         "endpoint: https://coins.llama.fi/block/{chain}/{timestamp}"],
    ], [3.2*cm, W-3.2*cm]),
]

# ── Build ───────────────────────────────────────────────────────────────────────
doc.build(story)
print(f"PDF 생성 완료: {OUTPUT_PATH}")
